version: '3.9'
services:
  #PHP Service
  gbaynham-archive-api:
    build:
      context: .
      dockerfile: dockerfiles/AppDockerfile
    container_name: gbaynham-archive-api
    tty: true
    restart: unless-stopped
    environment:
      SERVICE_NAME: gbaynham-archive-api
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "9090:9000"
    volumes:
      - ../gbaynham-archive-api/:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logs/php:/var/log/php/
    networks:
      - gbaynham-archive-network

  #Nginx Service
  gbaynham-archive-nginx:
    image: nginx:alpine
    container_name: gbaynham-archive-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "44443:443"
    volumes:
      - ../gbaynham-archive-api:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx/
    networks:
      - gbaynham-archive-network

  #Composer
  gbaynham-archive-composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - ../gbaynham-archive-api:/app
  #Node
  gbaynham-archive-node:
    image: node:14
    command: bash -c "npm install && npm run watch"
    working_dir: /app
    volumes:
      - ../gbaynham-archive-api:/app

  #MySQL Service
  gbaynham-archive-db:
    container_name: gbaynham-archive-db
    ports:
      - 33066:3306
    image: mariadb:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "r00t"
        MYSQL_DATABASE: gbaynham-archive
        MYSQL_USER: gbaynham-archive-user
        MYSQL_PASSWORD: xH8rWzXQ3Y82RwiWUxudK

    volumes:
      - gba-dbdata:/var/lib/mysql/
      - ./logs/mysql:/var/log/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - gbaynham-archive-network

  #Memcached
  gbaynham-archive-memcached:
    image: memcached
    ports:
      - 61211:11211

    command: memcached -m 1024m

  #RabbitMQ - Ubuntu image AToW
  gbaynham-archive-rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 35672:15672
    volumes:
        - gba-rabbitmq-data:/var/lib/rabbitmq/
        - ./logs/rabbitmq:/var/log/rabbitmq
    networks:
        - gbaynham-archive-network
  gbaynham-archive-phpstan:
    image: ghcr.io/phpstan/phpstan
    profiles:
      - testing
  gbaynham-archive-selenium:
    restart: 'no'
    image: selenium/standalone-firefox
    profiles:
      - testing
    ports:
      - 4445:4444

#Docker Networks
networks:
  gbaynham-archive-network:
    driver: bridge

#Volumes
volumes:
  gba-rabbitmq-data:
    driver: local
  gba-dbdata:
    driver: local